In [11]:
import pandas as pd
import pandera as pa

In [34]:
df = pd.read_csv("ocorrencia.csv", sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True, encoding='latin-1')
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,0,1,NÃO

In [3]:
df

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,80458,80458,80458,80458,ACIDENTE,-17.999.194,-51.642.861,JATAÍ,GO,...,2021-12-30,20:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5163,80452,80452,80452,80452,80452,ACIDENTE,-22.585.556,-50.753.889,MARACAÍ,SP,...,2021-12-31,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5164,80457,80457,80457,80457,80457,INCIDENTE GRAVE,-29.695.833,-51.081.667,NOVO HAMBURGO,RS,...,2021-12-31,11:59:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5165,80460,80460,80460,80460,80460,INCIDENTE,-25.403.333,-49.233.611,CURITIBA,PR,...,2021-12-31,15:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5166,80467,80467,80467,80467,80467,INCIDENTE,-93.675,-4.056.361.111.111,PETROLINA,PE,...,2021-12-31,20:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [13]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,0,1,NÃO

In [22]:
df.loc[df.ocorrencia_aerodromo == '###!', ['ocorrencia_aerodromo']] = pd.NA

In [26]:
df.loc[1:20,'ocorrencia_aerodromo']

1     SBGR
2     <NA>
3     <NA>
4     <NA>
5     <NA>
6     SDAI
7     SBBE
8     <NA>
9     SBUL
10    <NA>
11    SBPA
12    SBMA
13    <NA>
14    <NA>
15    <NA>
16    <NA>
17    SBBR
18    SNWC
19    <NA>
20    SBPR
Name: ocorrencia_aerodromo, dtype: object

ocorrencia_latitude
\t
***
****
*********
ocorrencia_longitude
\t
***
****
*********
ocorrencia_uf
**
ocorrencia_aerodromo
###!
####
****
*****
ocorrencia_hora
NULL
investigacao_aeronave_liberada
NULL
***
divulgacao_relatorio_numero
***
NULL
divulgacao_dia_publicacao
NULL

In [35]:
df.replace(['\t','***','****','*****','###!','####','NaN','NULL'], pd.NA, inplace=True)

In [39]:
df.isna().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1493
ocorrencia_longitude              1494
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              1905
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    1778
investigacao_status                257
divulgacao_relatorio_numero       3291
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         3816
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [ ]:
df.fillna(10, inplace=True)

In [42]:
df

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,<NA>,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,<NA>,<NA>,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,<NA>,<NA>,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,<NA>,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,<NA>,<NA>,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,80458,80458,80458,80458,ACIDENTE,-17.999.194,-51.642.861,JATAÍ,GO,...,2021-12-30,20:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5163,80452,80452,80452,80452,80452,ACIDENTE,-22.585.556,-50.753.889,MARACAÍ,SP,...,2021-12-31,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5164,80457,80457,80457,80457,80457,INCIDENTE GRAVE,-29.695.833,-51.081.667,NOVO HAMBURGO,RS,...,2021-12-31,11:59:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5165,80460,80460,80460,80460,80460,INCIDENTE,-25.403.333,-49.233.611,CURITIBA,PR,...,2021-12-31,15:12:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5166,80467,80467,80467,80467,80467,INCIDENTE,-93.675,-4.056.361.111.111,PETROLINA,PE,...,2021-12-31,20:30:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO

In [ ]:
df.replace([10], pd.NA, inplace=True)

In [ ]:
df.fillna(value={'total_recomendacoes':10}, inplace=True)